go_import_path: github.com/emccode/rexray

language: go

go:
  - 1.5.1

addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
      - .build/bin
  apt:
    packages:
    - rpm

before_script:
  - source .build/dependencies.sh

script:
  - make build-all

notifications:
  - slack: $SLACK_BUILDS

cache:
  apt: true
  directories:
    - $HOME/.opt
